import type { Metadata } from "next";
import localFont from "next/font/local";
import { Baskervville, Geist } from "next/font/google";
import "./globals.css";
import { JotaiProvider } from "@/lib/jotai-provider";
import { Suspense } from "react";
import ScrollToTop from "@/components/shared/scroll-to-top";
import LenisWrapper from "@/context/lenis-wrapper";
// import PageLoaderWrapper from "@/components/layout/page-loader/page-loader-wrapper";

const generalSans = localFont({
  src: "./fonts/GeneralSans-Variable.woff2",
  variable: "--font-general-sans",
  display: "swap",
});

// const libreBaskerville = Libre_Baskerville({
//   variable: "--font-baskerville",
//   subsets: ["latin"],
// });

const baskerville = Baskervville({
  variable: "--font-baskerville",
  subsets: ["latin"],
});

const snellRoundhand = localFont({
  src: "./fonts/SnellRoundhand.woff2",
  variable: "--font-snell-roundhand",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ATELIER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${generalSans.variable} ${baskerville.variable} ${snellRoundhand.variable} ${geistSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <JotaiProvider>
          {/* <PageLoaderWrapper> */}
          <Suspense>
            <ScrollToTop />
          </Suspense>
          <LenisWrapper />
          {children}
          {/* </PageLoaderWrapper> */}
        </JotaiProvider>
      </body>
    </html>
  );
}
